# fly.toml app configuration file generated for simple-l2-tut on 2024-09-16T10:42:13+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'simple-l2-tut'
primary_region = 'sin'

[services]
protocol = "tcp"
internal_port = 8000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']
[[services.ports]]
port = 8000

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[env]
PORT = "8000"
